// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqegmwatmpqzhjrujfcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZWdtd2F0bXBxemhqcnVqZmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTYyMjUsImV4cCI6MjA3MDMzMjIyNX0._dDl3JzKp_8Dra7Br-Nguxy8fwgt21aYmq6L9qbare8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});